export const timelineConstants = {
  GET_TIME_LINE_OF_SERVICE: {
    REQUEST: 'GET_TIME_LINE_OF_SERVICE_REQUEST',
    SUCCESS: 'GET_TIME_LINE_OF_SERVICE_SUCCESS',
    FAILURE: 'GET_TIME_LINE_OF_SERVICE_FAILURE',
  },
  GET_TIME_LINE_OF_ORGANIZATION: {
    REQUEST: 'GET_TIME_LINE_OF_ORGANIZATION_REQUEST',
    SUCCESS: 'GET_TIME_LINE_OF_ORGANIZATION_SUCCESS',
    FAILURE: 'GET_TIME_LINE_OF_ORGANIZATION_FAILURE',
  },
}; 