# Generated by Django 5.2.3 on 2025-06-29 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_user_has_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('operational', 'Operational'), ('degraded_performance', 'Degraded Performance'), ('partial_outage', 'Partial Outage'), ('major_outage', 'Major Outage')], default='operational', max_length=20)),
                ('publicly_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.organization', verbose_name='Organization')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization'], name='services_organiz_12bd44_idx'), models.Index(fields=['current_status'], name='services_current_88b8a9_idx'), models.Index(fields=['publicly_visible'], name='services_publicl_ee6b7f_idx'), models.Index(fields=['created_at'], name='services_created_22da02_idx')],
            },
        ),
    ]
