# Generated by Django 5.2.3 on 2025-06-29 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='investigating', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='services.service', verbose_name='Service')),
            ],
            options={
                'db_table': 'incidents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service'], name='incidents_service_827dd1_idx'), models.Index(fields=['status'], name='incidents_status_9db31b_idx'), models.Index(fields=['severity'], name='incidents_severit_667686_idx'), models.Index(fields=['created_at'], name='incidents_created_bc994b_idx'), models.Index(fields=['resolved_at'], name='incidents_resolve_a80445_idx')],
            },
        ),
    ]
