# Generated by Django 5.2.3 on 2025-06-28 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_username_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('team', 'Team Member'), ('user', 'User')], default='team', max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='users.organization')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invite_links',
                'indexes': [models.Index(fields=['token'], name='invite_link_token_acce4a_idx'), models.Index(fields=['created_by'], name='invite_link_created_27c149_idx'), models.Index(fields=['used_by'], name='invite_link_used_by_383a35_idx'), models.Index(fields=['expires_at'], name='invite_link_expires_73440e_idx')],
            },
        ),
    ]
