export const userConstants = {
  GET_USER: {
    REQUEST: 'GET_USER_REQUEST',
    SUCCESS: 'GET_USER_SUCCESS',
    FAILURE: 'GET_USER_FAILURE',
  },
  SIGN_UP: {
    REQUEST: 'SIGN_UP_REQUEST',
    SUCCESS: 'SIGN_UP_SUCCESS',
    FAILURE: 'SIGN_UP_FAILURE',
  },
  LOGIN: {
    REQUEST: 'LOGIN_REQUEST',
    SUCCESS: 'LOGIN_SUCCESS',
    FAILURE: 'LOGIN_FAILURE',
  },
  GENERATE_INVITE_LINK: {
    REQUEST: 'GENERATE_INVITE_LINK_REQUEST',
    SUCCESS: 'GENERATE_INVITE_LINK_SUCCESS',
    FAILURE: 'GENERATE_INVITE_LINK_FAILURE',
  },
  GET_TEAM_MEMBERS: {
    REQUEST: 'GET_TEAM_MEMBERS_REQUEST',
    SUCCESS: 'GET_TEAM_MEMBERS_SUCCESS',
    FAILURE: 'GET_TEAM_MEMBERS_FAILURE',
  },
  CLEAR_ERROR: 'CLEAR_ERROR',
  LOGOUT: 'LOGOUT',
};
